// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_hbNJPQaQw4AKhDmfdZpFjHnhMd3UCZo',
    appId: '1:714059208574:web:1aa71464607dc59d1f452f',
    messagingSenderId: '714059208574',
    projectId: 'fir-2024-auth',
    authDomain: 'fir-2024-auth.firebaseapp.com',
    storageBucket: 'fir-2024-auth.appspot.com',
    measurementId: 'G-7Y6DNH5NDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLZJBVj3y1EgfnAPNm9LEPzJ-NFf968zs',
    appId: '1:714059208574:android:f72c1fd1a88278a91f452f',
    messagingSenderId: '714059208574',
    projectId: 'fir-2024-auth',
    storageBucket: 'fir-2024-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh-ju0TOnA1pAl9NGIotCnB79N6LZhBmg',
    appId: '1:714059208574:ios:e0aaa836886796f21f452f',
    messagingSenderId: '714059208574',
    projectId: 'fir-2024-auth',
    storageBucket: 'fir-2024-auth.appspot.com',
    iosBundleId: 'com.example.firebaseAuth2024',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh-ju0TOnA1pAl9NGIotCnB79N6LZhBmg',
    appId: '1:714059208574:ios:e0aaa836886796f21f452f',
    messagingSenderId: '714059208574',
    projectId: 'fir-2024-auth',
    storageBucket: 'fir-2024-auth.appspot.com',
    iosBundleId: 'com.example.firebaseAuth2024',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_hbNJPQaQw4AKhDmfdZpFjHnhMd3UCZo',
    appId: '1:714059208574:web:8feef2e5b1ce0dda1f452f',
    messagingSenderId: '714059208574',
    projectId: 'fir-2024-auth',
    authDomain: 'fir-2024-auth.firebaseapp.com',
    storageBucket: 'fir-2024-auth.appspot.com',
    measurementId: 'G-5K1W6N8KLB',
  );
}
